Developer
persistence10/WorkBook pull request #1
Opened 2020-02-03 02:13 UTC by persistence10

2020-02-03 06:17 UTC, jungseungyeo requested changes

2020-02-03 06:17 UTC, jungseungyeo commented on practice/practice/main.swift
> +    }catch {
catch에서 error를 뽑아 내는 방법을 찾아보세요

2020-02-03 06:17 UTC, jungseungyeo commented on practice/practice/main.swift
> +enum ExceptionLog: String, Swift.Error {
String말고 Int를 받은 다음 CustomStringConvertible을 준수하여 작성해보세요
```
eunum ExceptionLog: Int, Swift.Error, CustomStringConvertible { }
```

2020-02-03 06:17 UTC, jungseungyeo commented on practice/practice/main.swift
> +    func matchYourAge (_ converionInt: Int) throws -> Int {
함수 역할이 Int To Int 입니다. 매칭된 이름을 반환하기 위해서는 String을 return하는것이 맞아보입니다.

2020-02-03 06:17 UTC, jungseungyeo commented on practice/practice/main.swift
> +        return 0
이 return이 호출 되는 경우가 있나요?

2020-02-04 05:22 UTC, persistence10 commented on practice/practice/main.swift
> +    }catch {
error 를 Swift.Error , CustomStringConverible protocol 준수하여 처리하였고, 
switch & enum 으로 error 로그 예외처리 진행 하였음.

2020-02-04 05:26 UTC, persistence10 commented on practice/practice/main.swift
> +enum ExceptionLog: String, Swift.Error {
CustomStringConvertible 프로토콜 준수하여 description : String 프로퍼티 통해 작성완료 하였음.

2020-02-04 05:29 UTC, persistence10 commented on practice/practice/main.swift
> +    func matchYourAge (_ converionInt: Int) throws -> Int {
return type 을 String 으로 변경 하였습니다.

2020-02-04 05:30 UTC, persistence10 commented on practice/practice/main.swift
> +        return 0
기존에 return type int type 에서, matchYourAge 함수를 String 으로 return type 변경하여 처리 하였음.

2020-02-04 05:45 UTC, jungseungyeo commented
리뷰 해주세요

2020-02-04 05:46 UTC, persistence10 commented
리뷰 끝

2020-02-04 05:47 UTC, merged